if(NOT GCC-8.1.0_CMAKE)
set(GCC-8.1.0_CMAKE TRUE)

set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_CXX_COMPILER_FORCED TRUE)
add_definitions(-DUNICODE -D_UNICODE)
string(APPEND CMAKE_EXE_LINKER_FLAGS " -municode")

endif(NOT GCC-8.1.0_CMAKE)
